parameters:
  - name: AzureSubscription
    type: string

steps:
  - task: filetransform@1
    displayname: "file transform: stub service application settings"
    inputs:
      folderpath: '$(pipeline.workspace)/ukhos100permitservicestubservice/*.zip'
      filetype: 'json'
      targetfiles: '**/appsettings.json'

  - task: azurewebapp@1
    displayname: "azure stub app deploy"
    inputs:
      azuresubscription: "${{ parameters.azuresubscription }}"
      apptype: webapp
      appname: "$(mock_web_app_name)"
      package: "$(pipeline.workspace)/ukhos100permitservicestubservice/ukho.s100permitservice.stubservice.zip"
           
  - task: AzureWebApp@1
    displayName: "Azure Api App Deploy"
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      appType: webApp
      appName: "$(WEB_APP_NAME)"
      package: "$(Pipeline.Workspace)/UKHOS100PermitServiceAPI/UKHOS100PermitServiceAPI.zip"
