parameters:
  - name: AzureSubscription
    type: string

steps:
  - task: FileTransform@1
    displayName: "File Transform: Stubs Service Application Settings"
    inputs:
      folderPath: '$(Pipeline.Workspace)/S100PermitServiceStubs/*.zip'
      fileType: 'json'
      targetFiles: '**/appsettings.json'

  - task: AzureWebApp@1
    displayName: "Azure Stubs App Deploy"
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      appType: webApp
      appName: "$(MOCK_WEB_APP_NAME)"
      package: "$(Pipeline.Workspace)/UKHOS100PermitServiceStubs/UKHO.S100PermitService.Stubs.zip"

  - task: FileTransform@1
    displayName: "File Transform: WebAppSettings"
    inputs:
      folderPath: '$(Pipeline.Workspace)/UKHO.S100PermitService.API/*.zip'
      fileType: 'json'
      targetFiles: '**/appsettings.json'
           
  - task: AzureWebApp@1
    displayName: "Azure Api App Deploy"
    inputs:
      azureSubscription: "${{ parameters.AzureSubscription }}"
      appType: webApp
      appName: "$(WEB_APP_NAME)"
      package: "$(Pipeline.Workspace)/UKHO.S100PermitService.API/UKHOS100PermitServiceAPI.zip"
